name: CI/CD Pipeline

on:
    push:
        branches:
            - development

jobs:
    merge-and-publish:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  ref: development

            # Setup Node.js environment
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            # Configure Git
            - name: Configure Git
              run: |
                  git config --global user.name 'github-actions'
                  git config --global user.email 'github-actions@github.com'

            # Authenticate with GitHub using default token
            - name: Authenticate with GitHub
              run: |
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

            # Fetch all branches
            - name: Fetch all branches
              run: git fetch --all

            # Checkout main branch
            - name: Checkout main branch
              run: git checkout main

            # Checkout main branch
            - name: Create or checkout main branch
              run: |
                if git show-ref --quiet refs/heads/main; then
                   git checkout main
                fi

            # Merge development into main
            - name: Merge development into main
              id: merge
              run: |
                git merge development --allow-unrelated-histories || true

            # Check for merge conflicts
            - name: Check for merge conflicts
              run: |
               if git ls-files -u | grep -q '^'; then
                 echo "::error::Merge conflict detected. Please resolve the conflict manually."
               exit 1
               fi

            # Push the merge commit
            - name: Push the merge commit
              if: success()
              run: |
                git commit -m "Merge branch 'development' into 'main'"
                git push origin main

            # Publish to npm
            - name: Publish to npm
              if: ${{ github.ref == 'refs/heads/main' }}
              run: |
                  npm install
                  npm run build
                  npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
