name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  merge-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: development

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.name 'abinash'
          git config --global user.email 'thakurabinash299@gmail.com'

      # Output repository information
      - name: Show repository info
        run: echo "Repository: ${{ github.repository }}"

      # Authenticate with GitHub using PAT
      - name: Authenticate with GitHub
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://github-actions:${GH_PAT}@github.com/${{ github.repository }}.git

      # Ensure main branch exists
      - name: Ensure main branch exists
        run: |
          if git show-ref --verify --quiet refs/heads/main; then
            echo "Branch 'main' exists."
          else
            echo "Branch 'main' does not exist. Creating 'main' branch."
            git checkout -b main
            git push origin main
          fi

      # Merge development into main
      - name: Merge development into main
        run: |
          git checkout main
          git merge development
          git push origin main

      # Publish to npm
      - name: Publish to npm
        if: github.ref == 'refs/heads/main'
        run: |
          npm install
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
